"""Added distance and temp units to User

Revision ID: 12b7a9b6a065
Revises: 45b10ad76f00
Create Date: 2026-08-13 12:45:33.905681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# For custom TypeAnnotations
import rungoal.models



# revision identifiers, used by Alembic.
revision: str = '12b7a9b6a065'
down_revision: Union[str, Sequence[str], None] = '45b10ad76f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_unit', sa.Enum('meters', 'miles', name='distanceunit'), nullable=True))
        batch_op.add_column(sa.Column('temperature_unit', sa.Enum('celsius', 'fahrenheit', name='temperatureunit'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('temperature_unit')
        batch_op.drop_column('distance_unit')

    # ### end Alembic commands ###
