"""RunSplitStats start and end time

Revision ID: 14bc04436fb8
Revises: 23b2976d61c3
Create Date: 2026-08-11 14:28:24.505277

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# For custom TypeAnnotations


# revision identifiers, used by Alembic.
revision: str = "14bc04436fb8"
down_revision: str | Sequence[str] | None = "23b2976d61c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create runsplitstats.end_secs column (nullable initially)
    with op.batch_alter_table("runsplitstats", schema=None, recreate="always") as batch_op:
        batch_op.add_column(
            sa.Column("end_secs", sa.Integer(), nullable=True), insert_after="split_secs"
        )

    # Copy existing values from split_secs into end_secs
    op.execute("UPDATE runsplitstats SET end_secs = split_secs")

    # Set end_secs to non-nullable and rename split_secs to start_secs
    with op.batch_alter_table("runsplitstats", schema=None) as batch_op:
        batch_op.alter_column("end_secs", existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column(
            "split_secs", existing_type=sa.Integer(), new_column_name="start_secs"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runsplitstats", schema=None) as batch_op:
        batch_op.alter_column(
            "start_secs", existing_type=sa.Integer(), new_column_name="split_secs"
        )
        batch_op.drop_column("end_secs")

    # ### end Alembic commands ###
