"""Allow null TrackPoint fields

Revision ID: 23b2976d61c3
Revises: a16c1fa95ad0
Create Date: 2026-08-09 13:57:02.113070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# For custom TypeAnnotations
import rungoal.models



# revision identifiers, used by Alembic.
revision: str = '23b2976d61c3'
down_revision: Union[str, Sequence[str], None] = 'a16c1fa95ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    with op.batch_alter_table('trackpoint', schema=None) as batch_op:
        batch_op.alter_column('lat_deg',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('lon_deg',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('alt_meters',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('distance_meters',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackpoint', schema=None) as batch_op:
        batch_op.alter_column('distance_meters',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('alt_meters',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('lon_deg',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('lat_deg',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
