"""Add RunSplitStats table

Revision ID: 2b3f64bcc8d0
Revises: 72f90d457e67
Create Date: 2026-07-25 11:21:43.552521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# For custom TypeAnnotations
import rungoal.models



# revision identifiers, used by Alembic.
revision: str = '2b3f64bcc8d0'
down_revision: Union[str, Sequence[str], None] = '72f90d457e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runsplitstats',
    sa.Column('split_secs', sa.Integer(), nullable=False),
    sa.Column('dist_meters', sa.Float(), nullable=False),
    sa.Column('gad_meters', sa.Float(), nullable=False),
    sa.Column('hr_avg', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runsplitstats')
    # ### end Alembic commands ###
