"""initial

Revision ID: 342b3e319ddc
Revises: 
Create Date: 2026-06-25 19:34:42.261135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision: str = '342b3e319ddc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_api_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_api_refresh_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('GOOGLE_HEALTH', 'RUNTRACKER', name='rundatasource'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('distance_millimeters', sa.Integer(), nullable=False),
    sa.Column('average_pace_seconds_per_meter', sa.Float(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_millimeters', sa.Integer(), nullable=True),
    sa.Column('active_duration', sa.Float(), nullable=False),
    sa.Column('avg_cadence_steps_per_minute', sa.Integer(), nullable=True),
    sa.Column('avg_stride_length_millimeters', sa.Integer(), nullable=True),
    sa.Column('avg_vertical_oscillation_millimeters', sa.Integer(), nullable=True),
    sa.Column('avg_vertical_ratio', sa.Float(), nullable=True),
    sa.Column('avg_ground_contact_time_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
