"""RunSplitStats non-nullable

Revision ID: 45b10ad76f00
Revises: 14bc04436fb8
Create Date: 2026-08-11 15:26:01.141318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# For custom TypeAnnotations
import rungoal.models



# revision identifiers, used by Alembic.
revision: str = '45b10ad76f00'
down_revision: Union[str, Sequence[str], None] = '14bc04436fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runsplitstats', schema=None) as batch_op:
        batch_op.alter_column('hr_avg',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('efficiency',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runsplitstats', schema=None) as batch_op:
        batch_op.alter_column('efficiency',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('hr_avg',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
