"""Added indices for run and runsplitstats

Revision ID: 481ded8fab63
Revises: 83ccf963f6bc
Create Date: 2026-07-28 13:02:02.814423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# For custom TypeAnnotations
import rungoal.models



# revision identifiers, used by Alembic.
revision: str = '481ded8fab63'
down_revision: Union[str, Sequence[str], None] = '83ccf963f6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('runsplitstats', schema=None) as batch_op:
        batch_op.create_index('idx_rss_run_efficiency', ['run_id', 'efficiency'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runsplitstats', schema=None) as batch_op:
        batch_op.drop_index('idx_rss_run_efficiency')

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_user_id'))

    # ### end Alembic commands ###
