"""Add Run.location and RunLocation.runs relationships

Revision ID: 544772e43962
Revises: 8a4ea0ffff75
Create Date: 2026-07-29 08:44:26.118649

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# For custom TypeAnnotations


# revision identifiers, used by Alembic.
revision: str = "544772e43962"
down_revision: Union[str, Sequence[str], None] = "8a4ea0ffff75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_run_location_id_runlocation", "runlocation", ["location_id"], ["osm_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_constraint("fk_run_location_id_runlocation", type_="foreignkey")
        batch_op.drop_column("location_id")

    # ### end Alembic commands ###
