"""Add Goal.name

Revision ID: 72f90d457e67
Revises: c3a91968d3b2
Create Date: 2026-07-20 08:51:27.489702

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# For custom TypeAnnotations


# revision identifiers, used by Alembic.
revision: str = "72f90d457e67"
down_revision: Union[str, Sequence[str], None] = "c3a91968d3b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goal", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE goal SET name = 'New Goal'")

    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.alter_column(
            "name", nullable=False, existing_type=sqlmodel.sql.sqltypes.AutoString()
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
