"""Added CachedArea and RunLocation tables

Revision ID: 8a4ea0ffff75
Revises: 481ded8fab63
Create Date: 2026-07-28 15:47:33.384972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# For custom TypeAnnotations
import rungoal.models



# revision identifiers, used by Alembic.
revision: str = '8a4ea0ffff75'
down_revision: Union[str, Sequence[str], None] = '481ded8fab63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cachedarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbox_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runlocation',
    sa.Column('osm_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('boundary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('osm_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runlocation')
    op.drop_table('cachedarea')
    # ### end Alembic commands ###
