"""Change runlocation.osm_id to str

Revision ID: a16c1fa95ad0
Revises: 809b91667a60
Create Date: 2026-07-30 18:19:40.234309

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# For custom TypeAnnotations


# revision identifiers, used by Alembic.
revision: str = "a16c1fa95ad0"
down_revision: Union[str, Sequence[str], None] = "809b91667a60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runlocation", schema=None) as batch_op:
        batch_op.alter_column(
            "osm_id",
            existing_type=sa.INTEGER(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "location_id",
            existing_type=sa.INTEGER(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runlocation", schema=None) as batch_op:
        batch_op.alter_column(
            "osm_id",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "location_id",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
