"""Initial DB

Revision ID: d4e6cd87b3cd
Revises: 
Create Date: 2026-06-27 15:16:51.420894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# For custom TypeAnnotations
import rungoal.models



# revision identifiers, used by Alembic.
revision: str = 'd4e6cd87b3cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_api_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_api_refresh_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('goal',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('GOOGLE_HEALTH', 'RUNTRACKER', name='rundatasource'), nullable=False),
    sa.Column('data_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', rungoal.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('end_time', rungoal.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('distance_millimeters', sa.Integer(), nullable=False),
    sa.Column('average_pace_seconds_per_meter', sa.Float(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_millimeters', sa.Integer(), nullable=True),
    sa.Column('active_duration', sa.Float(), nullable=False),
    sa.Column('avg_cadence_steps_per_minute', sa.Integer(), nullable=True),
    sa.Column('avg_stride_length_millimeters', sa.Integer(), nullable=True),
    sa.Column('avg_vertical_oscillation_millimeters', sa.Integer(), nullable=True),
    sa.Column('avg_vertical_ratio', sa.Float(), nullable=True),
    sa.Column('avg_ground_contact_time_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('elapsed_secs', sa.Float(), nullable=False),
    sa.Column('lat_deg', sa.Float(), nullable=False),
    sa.Column('lon_deg', sa.Float(), nullable=False),
    sa.Column('alt_meters', sa.Float(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trackpoint')
    op.drop_table('run')
    op.drop_table('goal')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
