"""empty message

Revision ID: ffa0c7aae1bf
Revises: 
Create Date: 2026-06-25 14:53:01.170611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision: str = 'ffa0c7aae1bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataSource', sa.Enum('GOOGLE_HEALTH', 'RUNTRACKER', name='rundatasource'), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('distMillimeters', sa.Integer(), nullable=False),
    sa.Column('averagePaceSecondsPerMeter', sa.Float(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('elevationGainMillimeters', sa.Integer(), nullable=True),
    sa.Column('activeDuration', sa.Integer(), nullable=False),
    sa.Column('avgCadenceStepsPerMinute', sa.Integer(), nullable=True),
    sa.Column('avgStrideLengthMillimeters', sa.Integer(), nullable=True),
    sa.Column('avgVerticalOscillationMillimeters', sa.Integer(), nullable=True),
    sa.Column('avgVerticalRatio', sa.Float(), nullable=True),
    sa.Column('avgGroundContactTimeDuration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatarUri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('googleApiAccessToken', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('googleApiRefreshToken', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('runsession')
    # ### end Alembic commands ###
