[project]
name = "Rungoal"
version = "0.9.5"
description = "Rungoal syncs your runs from Google Health, tracks running goals, and gives you all kinds of interesting statistics."
readme = "README.md"
authors = [
    { name = "Joshua Foster", email = "josh2112@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "google-api-python-client>=2.198.0",
    "google-auth-oauthlib>=1.4.0",
    "httpx>=0.28.1",
    "httpx-retries>=0.6.0",
    "mercantile>=1.2.1",
    "pillow>=12.3.0",
    "pydantic-settings>=2.14.2",
    "python-jose[cryptography]>=3.5.0",
    "sqids>=0.5.2",
    "sqlalchemy-utils>=0.42.1",
    "sqlmodel>=0.0.39",
    "typer>=0.27.0",
    "tzdata>=2026.3",
    "uvicorn>=0.52.0",
]

[project.scripts]
rungoal-cli = "rungoal.cli:app"

[tool.fastapi]
entrypoint = "rungoal.main:app"

[tool.pyright]
include = ["rungoal"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[lint]
select = ["ALL"]

[dependency-groups]
dev = [
    "fastapi-cli>=0.0.32",
]

[tool.ruff]
line-length = 100
