name: Build & Deploy to josh2112.com/rungoal

on:
    # Build when I push to master
    push:
        branches: [master]
    # Build manually (via Actions button)
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: "josh2112.com (NFSN)"
        env:
            DEST_PATH: "/home/protected/rungoal"
            # NFSN: Only 1 CPU core is available to us
            CARGO_BUILD_JOBS: 1
            # NFSN: Keep rust from picking up super-old OpenSSL in /usr/local
            OPENSSL_DIR: /usr
        steps:
            - name: Clone repo
              uses: actions/checkout@v7.0.0

            - name: Setup node.js
              uses: actions/setup-node@v6.5.0
              with:
                  node-version: "24"

            - name: Build frontend
              working-directory: ui
              run: |
                  npm ci
                  npm run build

            - name: Configure ssh/rsync
              run: |
                  mkdir -p ~/.ssh
                  printf '%s\n' "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ vars.HOST }} >> ~/.ssh/known_hosts
                  chmod 644 ~/.ssh/known_hosts
                  printf 'Host %s\n  HostName %s\n  User %s\n  IdentityFile ~/.ssh/id_rsa\n  IdentitiesOnly yes\n  StrictHostKeyChecking yes\n' \
                    "${{ vars.HOST }}" "${{ vars.HOST }}" "${{ secrets.USERNAME }}" > ~/.ssh/config
                  chmod 600 ~/.ssh/config

            - name: Deploy
              run: |
                  rsync -avzR --delete \
                  --exclude="daemon.sh" --exclude=".env" --exclude="client_secret.json" --exclude="/api/.venv" --exclude="/data" \
                  ui/dist/ \
                  api/ \
                  run-nfsn.sh \
                  ${{ vars.HOST }}:$DEST_PATH

            - name: Refresh Python venv
              # Set proces timeout to 10 minutes, rust builds can be very slow
              run: ssh ${{ vars.HOST }} "cd $DEST_PATH/api && ulimit -t 600 && uv sync --frozen --no-dev"

            - name: Stop backend service
              run: ssh ${{ vars.HOST }} "nfsn stop-daemon rungoal"

            - name: Create/migrate DB
              run: ssh ${{ vars.HOST }} "cd $DEST_PATH/api && mkdir -p ../data && uv run alembic upgrade head && chgrp -R web ../data && chmod -R g+w ../data"

            - name: Restart backend service
              run: ssh ${{ vars.HOST }} "chmod a+x run-nfsn.sh && nfsn start-daemon rungoal"
